### ISSUE TITLE
follow links to files

### ISSUE THREAD

**Issue by mooseyboots** [WillForan/zim-wiki-mode#10]
i think this is supposed to be implemented, but it doesn't work for me with multiple word links, as `ffap-string-at-point` (in `zim-wiki-ffap-file`) will just collect word at point if there are many words. almost all of my zim wiki links have multiple words.

a better implementation would fetch the whole link, probably using next/prev-property change for `docuwiki-link`, then strip the `[[ ]]`.

if i mark the link text, then the command works.

or is there a way to do this and i just can't see it for now?

**Comment by WillForan** [comment]
I think this is a the same issue as #1 -- though with a better (any) description

**Comment by WillForan** [comment]
follow up comments on #1 (even though this is the better reported issue). Here I think the ultimate issue is a now fixed: spaces in wiki path of link caused problems for following the wiki path at point. #1 was initially concerning wiki path at point using the display text part of the link instead of the path component. Both fixed by the same refactor in 5316f76  🤞
